INSERT INTO `comments` (`id`, `text`, `post_id`, `author_id`) VALUES (22, 'I had also gone to Concheto, but a fog caught me because the weather changes very quickly up there, and I returned. Now I\'m ambitious and I\'ve made it my number one goal to pass it in the summer.', 9, 4);
INSERT INTO `comments` (`id`, `text`, `post_id`, `author_id`) VALUES (23, 'We also went to the hut. Even the little one had a lot of fun and was by the lake all day.', 10, 2);
INSERT INTO `comments` (`id`, `text`, `post_id`, `author_id`) VALUES (24, 'I have passed it more than once or twice. There was always some kind of thrill until you passed it. However, there is no need for jokes in the mountains.', 9, 2);
INSERT INTO `comments` (`id`, `text`, `post_id`, `author_id`) VALUES (25, 'It is a paradise for children and not only. We rested with my wife and child. Gorgeous place and great location.', 10, 5);
INSERT INTO `comments` (`id`, `text`, `post_id`, `author_id`) VALUES (26, 'How can you go on foot, given that you can go to the Banderitsa hut and from there it is a 5-6 minute walk.', 11, 6);
INSERT INTO `comments` (`id`, `text`, `post_id`, `author_id`) VALUES (27, 'The man told you that he enjoys walking, and by the way, I have also done it, it is a great pleasure to go on foot, not by car, as he wrote.', 11, 4);
INSERT INTO `comments` (`id`, `text`, `post_id`, `author_id`) VALUES (28, 'I had heard about this waterfall. My curiosity made me jump on the car and see him. When I saw it and…….I was speechless. IT IS AWESOME!!! Whoever has the opportunity, let him go to Sandanski and maybe he will see him there for an hour.', 12, 4);
INSERT INTO `comments` (`id`, `text`, `post_id`, `author_id`) VALUES (29, 'Those meatballs must have been made by Aunt Danche. I actually ate them there from her, they are very nice. They are charcoal grilled!', 13, 6);
INSERT INTO `comments` (`id`, `text`, `post_id`, `author_id`) VALUES (30, 'Is there a long way to go after Sandanski? Does it look majestic?!?', 12, 7);
INSERT INTO `comments` (`id`, `text`, `post_id`, `author_id`) VALUES (31, 'Next to the Rozhensky Monastery, which is unique in its kind, is the grave of Yane Sandanski.', 14, 7);
INSERT INTO `comments` (`id`, `text`, `post_id`, `author_id`) VALUES (32, 'Does Aunt Danche still work there?!? She knows how to grill them, not just meatballs!', 13, 7);
INSERT INTO `comments` (`id`, `text`, `post_id`, `author_id`) VALUES (33, 'How far is it from Sandanski?', 9, 7);
INSERT INTO `comments` (`id`, `text`, `post_id`, `author_id`) VALUES (34, 'I have been several times, there is something magnetic there! I didn\'t feel like leaving there either.', 16, 9);
INSERT INTO `comments` (`id`, `text`, `post_id`, `author_id`) VALUES (35, 'How far is it from Sofia?', 9, 9);
INSERT INTO `comments` (`id`, `text`, `post_id`, `author_id`) VALUES (36, 'How far is it from Sofia?', 12, 9);
INSERT INTO `comments` (`id`, `text`, `post_id`, `author_id`) VALUES (37, 'I also visited this house and bought an amazing red wine. I\'m saving it for a special occasion.', 15, 9);
INSERT INTO `comments` (`id`, `text`, `post_id`, `author_id`) VALUES (45, 'Yes it is very nice!', 20, 7);
INSERT INTO `comments` (`id`, `text`, `post_id`, `author_id`) VALUES (46, 'It\'s very nice there and easy to get to.', 24, 9);
INSERT INTO `comments` (`id`, `text`, `post_id`, `author_id`) VALUES (47, 'Well maintained park.', 20, 9);
INSERT INTO `comments` (`id`, `text`, `post_id`, `author_id`) VALUES (48, 'Is it difficult to get there from Sandanski?', 25, 11);
